module.exports = {
  apps: [
    {
      name: "ghostops-backend",
      cwd: "/workspace/ghostops-web/backend",
      interpreter: "/workspace/ghostops-web/backend/venv/bin/python3",
      script: "/workspace/ghostops-web/backend/venv/bin/uvicorn",
      args: "main:app --host 0.0.0.0 --port 8000",
      watch: false,
      env: {
        NODE_ENV: "production",
      },
      error_file: "/workspace/ghostops-web/logs/backend-error.log",
      out_file: "/workspace/ghostops-web/logs/backend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: "ghostops-frontend",
      cwd: "/workspace/ghostops-web/frontend",
      script: ".next/standalone/server.js",
      interpreter: "node",
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: "3001",
        HOSTNAME: "0.0.0.0",
      },
      error_file: "/workspace/ghostops-web/logs/frontend-error.log",
      out_file: "/workspace/ghostops-web/logs/frontend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 8000,
      treekill: true,
    },
  ],
};
